apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: oce-agents
spec:
  limits:
    cpu: "32"
    memory: 128Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
  template:
    metadata:
      labels:
        oce-role: agents
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: oce-private
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: [arm64]
        - key: kubernetes.io/os
          operator: In
          values: [linux]
        - key: karpenter.sh/capacity-type
          operator: In
          values: [on-demand]
        - key: eks.amazonaws.com/instance-category
          operator: In
          values: [c, m, r]
        - key: eks.amazonaws.com/instance-generation
          operator: Gt
          values: ["6"]
        - key: eks.amazonaws.com/instance-cpu
          operator: In
          values: ["2"]
      expireAfter: 168h
      terminationGracePeriod: 5m
