apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: occ-gateway-rwo
provisioner: ebs.csi.eks.amazonaws.com
parameters:
  encrypted: "true"
  type: gp3
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: eks.amazonaws.com/compute-type
        values: [auto]
